# Generated by Django 5.0.6 on 2024-05-14 14:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_remove_offerfile_remote_url'), ('api', '0003_alter_commentfile_remote_url_and_more'), ('api', '0004_alter_commentfile_remote_url'), ('api', '0005_alter_comment_body_alter_issue_body_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField()),
                ('gh_id', models.CharField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(blank=True, max_length=8192)),
                ('state', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=255)),
                ('author_profile_pic', models.CharField(max_length=1023)),
                ('author_ujepsoft', models.CharField(blank=True, max_length=320)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('description', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=8191)),
                ('url', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('author_profile_pic', models.CharField(max_length=1023)),
                ('private', models.BooleanField(default=False)),
                ('collaborant', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField()),
                ('body', models.CharField(max_length=8191)),
                ('author', models.CharField(max_length=255)),
                ('author_profile_pic', models.CharField(max_length=1023)),
                ('author_ujepsoft', models.CharField(blank=True, max_length=320)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.issue')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(related_name='issues', to='api.label'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=8191)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('keywords', models.ManyToManyField(blank=True, related_name='offers', to='api.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('count', models.IntegerField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions_comment', to='api.comment')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionsIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('count', models.IntegerField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions_issue', to='api.issue')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.repo'),
        ),
        migrations.CreateModel(
            name='OfferFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='offer_files')),
                ('file_type', models.CharField(choices=[('file', 'file'), ('image', 'image')], max_length=5)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.offer')),
            ],
        ),
        migrations.CreateModel(
            name='IssueFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='issue_files')),
                ('file_type', models.CharField(choices=[('file', 'file'), ('image', 'image')], max_length=5)),
                ('remote_url', models.CharField(blank=True, default='', max_length=1024, validators=[django.core.validators.URLValidator()])),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.issue')),
            ],
        ),
        migrations.CreateModel(
            name='CommentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='comment_files')),
                ('file_type', models.CharField(choices=[('file', 'file'), ('image', 'image')], max_length=5)),
                ('remote_url', models.CharField(blank=True, default='', max_length=1024, validators=[django.core.validators.URLValidator()])),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.comment')),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='body',
            field=models.CharField(blank=True, max_length=8191),
        ),
    ]
