# Generated by Django 5.0.2 on 2024-02-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerfile',
            name='remote_url',
        ),
    ]
