# Generated by Django 4.2.4 on 2023-12-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_offer_files_file_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.offer'),
        ),
    ]
