# Generated by Django 5.0.2 on 2024-02-26 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_offerfile_remote_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentfile',
            name='remote_url',
            field=models.CharField(max_length=1024, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='issuefile',
            name='remote_url',
            field=models.CharField(blank=True, default='', max_length=1024, validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
    ]
