# Generated by Django 5.0.2 on 2024-02-26 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_commentfile_remote_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentfile',
            name='remote_url',
            field=models.CharField(blank=True, default='', max_length=1024, validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
    ]
