# Generated by Django 4.2.4 on 2023-12-12 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_label_reactions_repo_issue_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReactionsIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reactions',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='reactions',
        ),
        migrations.AddField(
            model_name='label',
            name='color',
            field=models.CharField(default='FFFFFF', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Reactions',
        ),
        migrations.AddField(
            model_name='reactionsissue',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions_issue', to='api.issue'),
        ),
        migrations.AddField(
            model_name='reactionscomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions_comment', to='api.comment'),
        ),
    ]
