# Generated by Django 4.2.4 on 2023-12-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reactionscomment_reactionsissue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='body',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
    ]
