# Generated by Django 4.2.4 on 2023-12-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_repo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='collaborant',
            field=models.BooleanField(default=True),
        ),
    ]
