# Generated by Django 4.2.4 on 2023-12-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_repo_collaborant'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='gh_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
