# Generated by Django 4.2.4 on 2023-12-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_issue_gh_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='gh_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='number',
            field=models.CharField(),
        ),
    ]
