# Generated by Django 5.0.2 on 2024-02-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_issue_body_alter_repo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_ujepsoft',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='issue',
            name='author_ujepsoft',
            field=models.CharField(blank=True, max_length=320),
        ),
    ]
