# Generated by Django 5.0.2 on 2024-02-20 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_commentfile_issuefile_offerfile_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentfile',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.comment'),
        ),
        migrations.AlterField(
            model_name='issuefile',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.issue'),
        ),
        migrations.AlterField(
            model_name='offerfile',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.offer'),
        ),
    ]
