# Build stage
FROM node:20.8.0-alpine AS builder

WORKDIR /app

COPY . .

RUN npm install && npx update-browserslist-db@latest && npm run build

# Runtime stage
FROM nginx:1.25.5-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY --from=builder /app/src/images /usr/share/nginx/html/src/images

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]

HEALTHCHECK --interval=30m --timeout=10s \
  CMD curl -f http://localhost:3000 || exit 1