services:
  ## Postgres
  postgresql:
    container_name: ujepsoft-postgresql
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ujepsoft
    volumes:
      - postgresql_data:/bitnami/postgresql
      - postgresql_pre_initdb:/docker-entrypoint-preinitdb.d
      - postgresql_initdb:/docker-entrypoint-initdb.d
    ports:
      - '127.0.0.1:5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30m
      timeout: 10s
      retries: 5
      start_period: 30s

  ## Redis
  redis:
    build: redis
    container_name: ujepsoft-redis
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD} --dir /data
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 30m
      timeout: 10s
      retries: 5
      start_period: 30s

  ## Backend
  backend:
    build: backend
    container_name: ujepsoft-backend
    volumes:
      - ./backend:/backend
    environment:
      - DJANGO_BASE_URL=http://localhost:8080
      - DJANGO_ALLOWED_HOSTS=localhost,webapp,10.0.0.16,192.168.1.2
      - DJANGO_DB_NAME=ujepsoft
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=postgres
      - DJANGO_DB_HOST=postgresql
      - DJANGO_DB_PORT=5432
      - DJANGO_REDIS_LOCATION=redis://redis:6379/1
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DJANGO_EMAIL_HOST=smtp.office365.com
      - DJANGO_EMAIL_PORT=587
      - DJANGO_EMAIL_USE_TLS=true
      - DJANGO_EMAIL_HOST_USER=ujepsoft@hotmail.com
      - DJANGO_EMAIL_HOST_PASSWORD=${DJANGO_EMAIL_HOST_PASSWORD}
      - DJANGO_EMAIL_FROM=ujepsoft@hotmail.com
      - DJANGO_SECRET=${DJANGO_SECRET}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USERNAME=matej-kaska
      - REDIS-TIMEOUT=15
      - MAX_FILE_SIZE=134217728 # 128 MB
      - MAX_TOTAL_FILES_SIZE=536870912 # 512 MB
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/api/test" ]
      interval: 30m
      timeout: 10s
      retries: 3
      start_period: 30s

  ## Frontend
  frontend:
    build: frontend
    container_name: ujepsoft-frontend
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    # Just for the dev server ws
    ports:
      - '3000:3000'
    depends_on:
      - backend
      - redis
    environment:
      - NODE_ENV=development
      - VITE_WEBSITE_URL=https://localhost:8080
      - VITE_GITHUB_USERNAME=matej-kaska
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000" ]
      interval: 30m
      timeout: 10s
      retries: 3
      start_period: 30s

  ## NGINX
  edge:
    build:
      context: edge
      dockerfile: Dockerfile
    container_name: ujepsoft-edge
    ports:
      - '8080:8080'
    volumes:
      - ./edge/ujepsoft.conf:/opt/bitnami/nginx/conf/server_blocks/ujepsoft.conf:ro
      - ./backend/media:/app/media
      - ./backend/staticfiles:/app/static
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080" ]
      interval: 30m
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  node_modules:
    driver: local
  postgresql_data:
    driver: local
  postgresql_initdb:
    driver: local
  postgresql_pre_initdb:
    driver: local
  redis:
    driver: local
