FROM python:alpine3.19

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

WORKDIR /backend

COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

ENTRYPOINT ["/backend/entrypoint.prod.sh"]
CMD ["gunicorn", "--bind", ":8000", "--workers", "3", "backend.wsgi:application"]