# Generated by Django 4.2.4 on 2023-08-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduklub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingunit',
            name='alternatives',
            field=models.ManyToManyField(to='eduklub.teachingunit'),
        ),
    ]
