# Generated by Django 4.2.4 on 2023-08-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduklub', '0002_alter_teachingunit_alternatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
