# Generated by Django 4.2.4 on 2023-09-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduklub', '0003_lesson_is_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_recommended',
        ),
        migrations.AddField(
            model_name='teachingunit',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='favoritelist',
            name='teaching_units',
            field=models.ManyToManyField(blank=True, related_name='favorite_lists', to='eduklub.teachingunit'),
        ),
        migrations.AlterField(
            model_name='teachingunit',
            name='advice_urls',
            field=models.ManyToManyField(blank=True, related_name='advice_urls', to='eduklub.linkurl'),
        ),
        migrations.AlterField(
            model_name='teachingunit',
            name='guide_urls',
            field=models.ManyToManyField(blank=True, related_name='guide_urls', to='eduklub.linkurl'),
        ),
        migrations.AlterField(
            model_name='teachingunit',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='teaching_units', to='eduklub.tag'),
        ),
    ]
