# Generated by Django 4.2.4 on 2023-10-08 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduklub', '0004_remove_lesson_is_recommended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='teaching_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='eduklub.teachingunit'),
        ),
    ]
