# Generated by Django 4.2.4 on 2023-10-08 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduklub', '0006_trigram_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teaching_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduklub.teachingunit'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='curriculums',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='eduklub.curriculum'),
        ),
    ]
