# Generated by Django 4.2.4 on 2023-10-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduklub', '0007_curriculum_alter_lesson_teaching_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='curriculums',
        ),
        migrations.AddField(
            model_name='teachingunit',
            name='curriculums',
            field=models.ManyToManyField(blank=True, related_name='teaching_units', to='eduklub.curriculum'),
        ),
    ]
