# Generated by Django 4.2.4 on 2023-10-22 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduklub', '0008_remove_lesson_curriculums_teachingunit_curriculums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teaching_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='eduklub.teachingunit'),
        ),
    ]
