# Generated by Django 4.2.4 on 2023-10-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduklub', '0009_alter_curriculum_name_alter_lesson_teaching_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingunit',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
