# Generated by Django 4.2.4 on 2023-10-29 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eduklub', '0010_teachingunit_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingunit',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
