# Generated by Django 5.0.8 on 2024-09-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0003_registrationcode_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
